// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2OAkIj4TlTuHho2HF9GsICggXW_lcsNs',
    appId: '1:824001307713:web:06519b2b259d798be392c0',
    messagingSenderId: '824001307713',
    projectId: 'news-e4556',
    authDomain: 'news-e4556.firebaseapp.com',
    storageBucket: 'news-e4556.appspot.com',
    measurementId: 'G-F7DP2R1WXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbTYh9ryxFE6ndXJNWntFKrFES5y2HMto',
    appId: '1:824001307713:android:283573268e8bec5ae392c0',
    messagingSenderId: '824001307713',
    projectId: 'news-e4556',
    storageBucket: 'news-e4556.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAXjv3iJbxfyR-EbMDUK8ytFKdyiIGxhQ',
    appId: '1:824001307713:ios:d473d0361428089fe392c0',
    messagingSenderId: '824001307713',
    projectId: 'news-e4556',
    storageBucket: 'news-e4556.appspot.com',
    iosClientId: '824001307713-tegtuafs67httbmnu2h9vb0h53vs5mn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.news',
  );
}
